apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n184

resources:
  - namespace.yaml
  - rbac.yaml
  - redis.yaml
  - memory-palace-pv.yaml
  - api-secrets.yaml
  - controller.yaml
  - honore.yaml
  - keda-vautrin.yaml
